package router

import (
	"github.com/gin-gonic/gin"
	"github.com/tokenrouter/tokenrouter/internal/auth"
	"github.com/tokenrouter/tokenrouter/internal/httpapi/handlers/accounts"
	"github.com/tokenrouter/tokenrouter/internal/httpapi/handlers/catalog"
	"github.com/tokenrouter/tokenrouter/internal/httpapi/handlers/channels"
	"github.com/tokenrouter/tokenrouter/internal/httpapi/handlers/commerce"
	"github.com/tokenrouter/tokenrouter/internal/httpapi/handlers/operations"
	relayhandlers "github.com/tokenrouter/tokenrouter/internal/httpapi/handlers/relay"
	settingshandlers "github.com/tokenrouter/tokenrouter/internal/httpapi/handlers/settings"
	"github.com/tokenrouter/tokenrouter/internal/httpapi/middleware"
)

// setupDashboardRouter registers the admin/root dashboard API.
func setupDashboardRouter(r *gin.Engine) {
	admin := r.Group("/api")
	admin.Use(middleware.GlobalRateLimit(), middleware.AdminAuth())
	admin.GET("/authz/catalog", accounts.GetPermissionCatalog)
	admin.GET("/channel", middleware.RequirePermission(auth.ChannelRead), channels.GetChannels)
	admin.GET("/channel/", middleware.RequirePermission(auth.ChannelRead), channels.GetChannels)
	admin.POST("/channel", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.AddChannel)
	admin.POST("/channel/", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.AddChannel)
	admin.GET("/channel/search", middleware.RequirePermission(auth.ChannelRead), channels.SearchChannels)
	admin.GET("/channel/models", middleware.RequirePermission(auth.ChannelRead), channels.ChannelListModels)
	admin.GET("/channel/models_enabled", middleware.RequirePermission(auth.ChannelRead), channels.EnabledListModels)
	admin.GET("/channel/ops", middleware.RequirePermission(auth.ChannelRead), channels.GetChannelOps)
	admin.GET("/channel/test", middleware.RequirePermission(auth.ChannelOperate), channels.TestAllChannels)
	admin.GET("/channel/test/:id", middleware.RequirePermission(auth.ChannelOperate), channels.TestChannel)
	admin.GET("/channel/update_balance", middleware.RequirePermission(auth.ChannelOperate), channels.UpdateAllChannelsBalance)
	admin.GET("/channel/update_balance/:id", middleware.RequirePermission(auth.ChannelOperate), channels.UpdateChannelBalance)
	admin.POST("/channel/status/batch", middleware.RequirePermission(auth.ChannelOperate), channels.BatchUpdateChannelStatus)
	admin.POST("/channel/:id/status", middleware.RequirePermission(auth.ChannelOperate), channels.UpdateChannelStatus)
	admin.DELETE("/channel/disabled", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.DeleteDisabledChannel)
	admin.POST("/channel/tag/disabled", middleware.RequirePermission(auth.ChannelOperate), channels.DisableTagChannels)
	admin.POST("/channel/tag/enabled", middleware.RequirePermission(auth.ChannelOperate), channels.EnableTagChannels)
	admin.PUT("/channel/tag", middleware.RequirePermission(auth.ChannelWrite), channels.EditTagChannels)
	admin.POST("/channel/batch", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.DeleteChannelBatch)
	admin.POST("/channel/fix", middleware.RequirePermission(auth.ChannelOperate), channels.FixChannelsAbilities)
	admin.GET("/channel/fetch_models/:id", middleware.RequirePermission(auth.ChannelOperate), channels.FetchUpstreamModels)
	admin.POST("/channel/fetch_models", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.FetchModels)
	admin.POST("/channel/batch/tag", middleware.RequirePermission(auth.ChannelWrite), channels.BatchSetChannelTag)
	admin.GET("/channel/tag/models", middleware.RequirePermission(auth.ChannelRead), channels.GetTagModels)
	admin.POST("/channel/copy/:id", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.CopyChannel)
	admin.POST("/channel/multi_key/manage", middleware.RequirePermission(auth.ChannelOperate), channels.ManageMultiKeys)
	admin.POST("/channel/upstream_updates/apply", middleware.RequirePermission(auth.ChannelWrite), channels.ApplyChannelUpstreamModelUpdates)
	admin.POST("/channel/upstream_updates/apply_all", middleware.RequirePermission(auth.ChannelWrite), channels.ApplyAllChannelUpstreamModelUpdates)
	admin.POST("/channel/upstream_updates/detect", middleware.RequirePermission(auth.ChannelOperate), channels.DetectChannelUpstreamModelUpdates)
	admin.POST("/channel/upstream_updates/detect_all", middleware.RequirePermission(auth.ChannelOperate), channels.DetectAllChannelUpstreamModelUpdates)
	admin.POST("/channel/:id/codex/refresh", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.RefreshCodexChannelCredential)
	admin.GET("/channel/:id/codex/usage", middleware.RequirePermission(auth.ChannelRead), channels.GetCodexChannelUsage)
	admin.GET("/channel/:id/codex/usage/reset-credits", middleware.RequirePermission(auth.ChannelRead), channels.GetCodexChannelRateLimitResetCredits)
	admin.POST("/channel/:id/codex/usage/reset", middleware.RequirePermission(auth.ChannelOperate), channels.ResetCodexChannelUsage)
	admin.POST("/channel/ollama/pull", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.OllamaPullModel)
	admin.POST("/channel/ollama/pull/stream", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.OllamaPullModelStream)
	admin.DELETE("/channel/ollama/delete", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.OllamaDeleteModel)
	admin.GET("/channel/ollama/version/:id", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.OllamaVersion)
	admin.GET("/channel/:id", middleware.RequirePermission(auth.ChannelRead), channels.GetChannel)
	admin.PUT("/channel", middleware.RequirePermission(auth.ChannelWrite), channels.UpdateChannel)
	admin.PUT("/channel/", middleware.RequirePermission(auth.ChannelWrite), channels.UpdateChannel)
	admin.DELETE("/channel/:id", middleware.RequirePermission(auth.ChannelSensitiveWrite), channels.DeleteChannel)
	admin.POST("/channel/:id/key", middleware.RootAuth(), middleware.CriticalRateLimit(),
		middleware.DisableCache(), middleware.SecureVerificationRequired(), channels.GetChannelKey)
	admin.GET("/ability", middleware.RequirePermission(auth.ChannelRead), channels.GetAbilities)
	admin.POST("/ability", middleware.RequirePermission(auth.ChannelWrite), channels.AddAbility)
	admin.DELETE("/ability", middleware.RequirePermission(auth.ChannelWrite), channels.DeleteAbility)
	admin.GET("/user", accounts.GetUsers)
	admin.GET("/user/", accounts.GetUsers)
	admin.POST("/user/", accounts.CreateUser)
	admin.GET("/user/search", accounts.SearchUsers)
	admin.GET("/user/topup", commerce.GetAllTopUps)
	admin.POST("/user/topup/complete", middleware.CriticalRateLimit(), commerce.AdminCompleteTopUp)
	admin.GET("/user/:id", accounts.GetUser)
	admin.PUT("/user", accounts.UpdateUser)
	admin.PUT("/user/", accounts.UpdateUser)
	admin.POST("/user/manage", accounts.ManageUser)
	admin.GET("/user/:id/oauth/bindings", accounts.GetUserOAuthBindingsByAdmin)
	admin.DELETE("/user/:id/oauth/bindings/:provider_id", accounts.UnbindCustomOAuthByAdmin)
	admin.DELETE("/user/:id/bindings/:binding_type", accounts.AdminClearUserBinding)
	admin.DELETE("/user/:id", accounts.AdminDeleteUser)
	admin.DELETE("/user/:id/reset_passkey", accounts.AdminResetPasskey)
	admin.DELETE("/user/:id/2fa", accounts.AdminDisable2FA)
	admin.GET("/user/2fa/stats", accounts.Admin2FAStats)
	admin.GET("/log", operations.GetLogs)
	admin.GET("/log/", operations.GetLogs)
	admin.GET("/log/stat", operations.GetLogsStat)
	admin.GET("/log/channel_affinity_usage_cache", channels.GetChannelAffinityUsageCacheStats)
	admin.GET("/log/search", operations.SearchAllLogs)
	admin.GET("/mj/", relayhandlers.GetAllMidjourney)
	admin.GET("/task/", relayhandlers.GetAllTask)
	admin.GET("/group/", catalog.GetGroups)
	modelMetadata := admin.Group("/models")
	modelMetadata.GET("/sync_upstream/preview", catalog.SyncUpstreamPreview)
	modelMetadata.POST("/sync_upstream", catalog.SyncUpstreamModels)
	modelMetadata.GET("/missing", catalog.GetMissingModels)
	modelMetadata.GET("/search", catalog.SearchModelsMeta)
	modelMetadata.GET("/", catalog.GetAllModelsMeta)
	modelMetadata.GET("/:id", catalog.GetModelMeta)
	modelMetadata.POST("/", catalog.CreateModelMeta)
	modelMetadata.PUT("/", catalog.UpdateModelMeta)
	modelMetadata.DELETE("/:id", catalog.DeleteModelMeta)
	vendorMetadata := admin.Group("/vendors")
	vendorMetadata.GET("/", catalog.GetAllVendors)
	vendorMetadata.GET("/search", catalog.SearchVendors)
	vendorMetadata.GET("/:id", catalog.GetVendorMeta)
	vendorMetadata.POST("/", catalog.CreateVendorMeta)
	vendorMetadata.PUT("/", catalog.UpdateVendorMeta)
	vendorMetadata.DELETE("/:id", catalog.DeleteVendorMeta)
	deployments := admin.Group("/deployments")
	deployments.GET("/settings", catalog.GetModelDeploymentSettings)
	deployments.POST("/settings/test-connection", catalog.TestIoNetConnection)
	deployments.GET("/", catalog.GetAllDeployments)
	deployments.GET("/search", catalog.SearchDeployments)
	deployments.POST("/test-connection", catalog.TestIoNetConnection)
	deployments.GET("/hardware-types", catalog.GetHardwareTypes)
	deployments.GET("/locations", catalog.GetLocations)
	deployments.GET("/available-replicas", catalog.GetAvailableReplicas)
	deployments.POST("/price-estimation", catalog.GetPriceEstimation)
	deployments.GET("/check-name", catalog.CheckClusterNameAvailability)
	deployments.POST("/", catalog.CreateDeployment)
	deployments.GET("/:id", catalog.GetDeployment)
	deployments.GET("/:id/logs", catalog.GetDeploymentLogs)
	deployments.GET("/:id/containers", catalog.ListDeploymentContainers)
	deployments.GET("/:id/containers/:container_id", catalog.GetContainerDetails)
	deployments.PUT("/:id", catalog.UpdateDeployment)
	deployments.PUT("/:id/name", catalog.UpdateDeploymentName)
	deployments.POST("/:id/extend", catalog.ExtendDeployment)
	deployments.DELETE("/:id", catalog.DeleteDeployment)
	prefillGroup := admin.Group("/prefill_group")
	prefillGroup.GET("/", catalog.GetPrefillGroups)
	prefillGroup.POST("/", catalog.CreatePrefillGroup)
	prefillGroup.PUT("/", catalog.UpdatePrefillGroup)
	prefillGroup.DELETE("/:id", catalog.DeletePrefillGroup)
	// House extension: admin dashboard counters (no reference counterpart;
	// the reference /api/data is the quota histogram above).
	admin.GET("/dashboard/stats", operations.GetDashboardData)

	admin.GET("/redemption", commerce.GetRedemptions)
	admin.GET("/redemption/", commerce.GetRedemptions)
	admin.GET("/redemption/search", commerce.SearchRedemptions)
	admin.GET("/redemption/:id", commerce.GetRedemption)
	admin.POST("/redemption", commerce.CreateRedemption)
	admin.POST("/redemption/", commerce.CreateRedemption)
	admin.PUT("/redemption", commerce.UpdateRedemption)
	admin.PUT("/redemption/", commerce.UpdateRedemption)
	admin.DELETE("/redemption/invalid", commerce.DeleteInvalidRedemption)
	admin.DELETE("/redemption/:id", commerce.DeleteRedemption)
	admin.POST("/subscription/plan", commerce.CreateSubscriptionPlan)
	admin.POST("/admin/subscription/plan", commerce.CreateSubscriptionPlan)
	admin.GET("/instance", operations.GetSystemInstances)

	// System options contain credentials and billing controls; the reference
	// exposes this entire surface to root operators only.
	optionRoute := r.Group("/api/option")
	optionRoute.Use(middleware.GlobalRateLimit(), middleware.RootAuth())
	optionRoute.GET("/", settingshandlers.GetOptions)
	optionRoute.PUT("/", settingshandlers.UpdateOptions)
	optionRoute.PUT("/smtp", settingshandlers.UpdateSMTPSettings)
	optionRoute.POST("/payment_compliance", commerce.ConfirmPaymentCompliance)
	optionRoute.GET("/channel_affinity_cache", channels.GetChannelAffinityCacheStats)
	optionRoute.DELETE("/channel_affinity_cache", channels.ClearChannelAffinityCache)
	optionRoute.POST("/rest_model_ratio", commerce.ResetModelRatio)
	optionRoute.GET("/waffo-pancake/catalog", commerce.ListWaffoPancakeCatalog)
	optionRoute.POST("/waffo-pancake/pair", commerce.CreateWaffoPancakePair)
	optionRoute.POST("/waffo-pancake/save", commerce.SaveWaffoPancake)
	optionRoute.POST("/waffo-pancake/subscription-product", commerce.CreateWaffoPancakeSubscriptionProduct)
	optionRoute.GET("/waffo-pancake/subscription-product-options", commerce.ListWaffoPancakeSubscriptionProductOptions)

	// Custom OAuth provider administration (root-only).
	customOAuth := r.Group("/api/custom-oauth-provider")
	customOAuth.Use(middleware.GlobalRateLimit(), middleware.RootAuth())
	customOAuth.POST("/discovery", accounts.FetchCustomOAuthDiscovery)
	customOAuth.GET("/", accounts.GetCustomOAuthProviders)
	customOAuth.GET("/:id", accounts.GetCustomOAuthProvider)
	customOAuth.POST("/", accounts.CreateCustomOAuthProvider)
	customOAuth.PUT("/:id", accounts.UpdateCustomOAuthProvider)
	customOAuth.DELETE("/:id", accounts.DeleteCustomOAuthProvider)

	// Runtime performance and local maintenance controls (root-only). The
	// destructive actions also use the critical limiter because GC and bounded
	// filesystem cleanup are intentionally synchronous operator operations.
	performance := r.Group("/api/performance")
	performance.Use(middleware.GlobalRateLimit(), middleware.RootAuth(), middleware.DisableCache())
	performance.GET("/stats", operations.GetPerformanceStats)
	performance.DELETE("/disk_cache", middleware.CriticalRateLimit(), operations.ClearDiskCache)
	performance.POST("/reset_stats", middleware.CriticalRateLimit(), operations.ResetPerformanceStats)
	performance.POST("/gc", middleware.CriticalRateLimit(), operations.ForceGC)
	performance.GET("/logs", operations.GetLogFiles)
	performance.DELETE("/logs", middleware.CriticalRateLimit(), operations.CleanupLogFiles)

	// Root-only upstream pricing comparison. Outbound destinations are
	// validated and dialed through the SSRF-safe direct transport in the
	// service; responses are explicitly non-cacheable operator data.
	ratioSync := r.Group("/api/ratio_sync")
	ratioSync.Use(middleware.GlobalRateLimit(), middleware.RootAuth(), middleware.DisableCache())
	ratioSync.GET("/channels", channels.GetSyncableChannels)
	ratioSync.POST("/fetch", channels.FetchUpstreamRatios)

	// System-task and system-info administration (root-only).
	systemTask := r.Group("/api/system-task")
	systemTask.Use(middleware.RootAuth())
	systemTask.POST("/log-cleanup", middleware.CriticalRateLimit(), operations.CreateLogCleanupSystemTask)
	systemTask.GET("/list", operations.ListSystemTasks)
	systemTask.GET("/current", operations.GetCurrentSystemTask)
	systemTask.GET("/:task_id", operations.GetSystemTask)

	systemInfo := r.Group("/api/system-info")
	systemInfo.Use(middleware.RootAuth())
	systemInfo.GET("/instances", operations.ListSystemInstances)
	systemInfo.DELETE("/stale-instances", operations.DeleteStaleSystemInstances)
	systemInfo.DELETE("/instances/:node_name", operations.DeleteStaleSystemInstance)

	// Durable accounting exceptions expose only a whitelisted, secret-free
	// snapshot. Financial state changes are root-only and append an atomic
	// primary-database audit event before returning success.
	relayQuotaReview := r.Group("/api/relay-quota-reservations")
	relayQuotaReview.Use(middleware.GlobalRateLimit(), middleware.RootAuth(), middleware.DisableCache())
	relayQuotaReview.GET("/manual-review", relayhandlers.ListManualReviewRelayQuotaReservations)
	relayQuotaReview.GET("/manual-review/:reservation_id", relayhandlers.GetManualReviewRelayQuotaReservation)
	relayQuotaReview.POST("/manual-review/:reservation_id/retry", middleware.CriticalRateLimit(),
		relayhandlers.RetryManualReviewRelayQuotaReservation)
	relayQuotaReview.POST("/manual-review/:reservation_id/resolve", middleware.CriticalRateLimit(),
		relayhandlers.ResolveManualReviewRelayQuotaReservation)

	// Subscription administration (plans + user subscriptions).
	subAdmin := r.Group("/api/subscription/admin")
	subAdmin.Use(middleware.AdminAuth())
	subAdmin.GET("/plans", commerce.AdminListSubscriptionPlans)
	subAdmin.POST("/plans", commerce.AdminCreateSubscriptionPlan)
	subAdmin.PUT("/plans/:id", commerce.AdminUpdateSubscriptionPlan)
	subAdmin.PATCH("/plans/:id", commerce.AdminUpdateSubscriptionPlanStatus)
	subAdmin.POST("/bind", commerce.AdminBindSubscription)
	subAdmin.POST("/plans/:id/subscriptions/reset", commerce.AdminResetPlanSubscriptions)
	subAdmin.GET("/users/:id/subscriptions", commerce.AdminListUserSubscriptions)
	subAdmin.POST("/users/:id/subscriptions", commerce.AdminCreateUserSubscription)
	subAdmin.POST("/users/:id/subscriptions/reset", commerce.AdminResetUserSubscriptionsByPlan)
	subAdmin.POST("/user_subscriptions/:id/invalidate", commerce.AdminInvalidateUserSubscription)
	subAdmin.DELETE("/user_subscriptions/:id", commerce.AdminDeleteUserSubscription)
	subAdmin.POST("/user_subscriptions/:id/entitlement-review/resolve", middleware.CriticalRateLimit(), middleware.RootAuth(),
		commerce.ResolveLegacySubscriptionEntitlementReview)
}
