package store

// AllModels is the ordered list of entities passed to AutoMigrate.
var AllModels = []any{
	&User{},
	&Token{},
	&Channel{},
	&Ability{},
	&Option{},
	&Redemption{},
	&Log{},
	&AuditLogOutbox{},
	&Midjourney{},
	&TopUp{},
	&QuotaData{},
	&Task{},
	&JimengTaskOperation{},
	&TaskOperation{},
	&Model{},
	&Vendor{},
	&PrefillGroup{},
	&Setup{},
	&TwoFA{},
	&TwoFABackupCode{},
	&Checkin{},
	&SubscriptionPlan{},
	&SubscriptionOrder{},
	&UserSubscription{},
	&SubscriptionPreConsumeRecord{},
	&RelayQuotaReservationRecord{},
	&RelayQuotaReservationReviewEvent{},
	&CustomOAuthProvider{},
	&UserOAuthBinding{},
	&PerfMetric{},
	&SystemInstance{},
	&SystemTask{},
	&SystemTaskLock{},
	&CasbinRule{},
	&AuthzRole{},
	&UserSession{},
	&AuthFlow{},
	&ExternalIdentityClaim{},
	&PasskeyCredential{},
}
