package store

// Relay quota reservation lifecycle states. A held row records the
// pre-authorization decision but has not reached an upstream. It normally owns
// wallet/subscription and limited-token holds; an explicitly marked ordinary
// trust-quota row deliberately owns zero holds. A dispatched row may represent
// accepted work and is therefore never expired into an automatic refund.
// Pending rows carry a durable operation intent and may be retried after their
// processing lease expires. Terminal rows are immutable accounting markers;
// manual_review retains the decision and error details for operator action
// after bounded automatic retries.
const (
	RelayQuotaReservationStatusHeld              = "held"
	RelayQuotaReservationStatusDispatched        = "dispatched"
	RelayQuotaReservationStatusPendingSettlement = "pending_settlement"
	RelayQuotaReservationStatusPendingRefund     = "pending_refund"
	RelayQuotaReservationStatusSettled           = "settled"
	RelayQuotaReservationStatusRefunded          = "refunded"
	RelayQuotaReservationStatusReversed          = "reversed"
	RelayQuotaReservationStatusManualReview      = "manual_review"
)

const (
	RelayQuotaReservationOperationSettle  = "settle"
	RelayQuotaReservationOperationRefund  = "refund"
	RelayQuotaReservationOperationReverse = "reverse"
)

// Violation-fee state is independent from the reservation lifecycle because a
// safety rejection is only known after the ordinary reservation has already
// reached its terminal refunded state. A separately committed pending intent
// makes the post-refund financial action crash-visible; charged is only written
// in the same transaction as every balance/counter update and its audit outbox.
const (
	RelayQuotaViolationFeeStatusPending      = "pending"
	RelayQuotaViolationFeeStatusCharged      = "charged"
	RelayQuotaViolationFeeStatusManualReview = "manual_review"
)

// RelayQuotaReservationRecord is the primary-database accounting ledger for
// one relay request reservation. ReservationID is generated by the server and
// doubles as the idempotency key for subscription pre-consume records.
type RelayQuotaReservationRecord struct {
	ID             int64  `json:"id" gorm:"primaryKey;autoIncrement"`
	ReservationID  string `json:"reservation_id" gorm:"type:varchar(64);not null;uniqueIndex"`
	UserID         int    `json:"user_id" gorm:"not null;index"`
	TokenID        int    `json:"token_id" gorm:"index"`
	TokenUnlimited bool   `json:"token_unlimited" gorm:"not null;default:false"`
	// TrustQuotaBypassed is an explicit accounting invariant, not a derived
	// display flag. When true, an ordinary wallet-funded relay intentionally
	// created no user or limited-token hold because both live balances were
	// above the configured trust threshold. Keeping the marker durable lets
	// recovery distinguish that valid zero-hold state from a corrupt/missing
	// reservation.
	TrustQuotaBypassed bool   `json:"trust_quota_bypassed" gorm:"not null;default:false"`
	ChannelID          int    `json:"channel_id" gorm:"index"`
	FundingSource      string `json:"funding_source" gorm:"type:varchar(32);not null"`
	RequestedQuota     int    `json:"requested_quota" gorm:"not null"`
	ReservedQuota      int    `json:"reserved_quota" gorm:"not null"`
	TokenReserved      int    `json:"token_reserved" gorm:"not null"`
	SubscriptionID     int    `json:"subscription_id" gorm:"index"`
	// UsageEpoch is copied from the subscription/pre-consume ledger at reserve
	// time and fences delayed settlement/refund across quota-window resets.
	UsageEpoch     int64  `json:"usage_epoch" gorm:"type:bigint;not null;default:0"`
	Status         string `json:"status" gorm:"type:varchar(32);not null;index:idx_relay_quota_retry,priority:1"`
	Operation      string `json:"operation" gorm:"type:varchar(16)"`
	ActualQuota    int    `json:"actual_quota"`
	Attempts       int    `json:"attempts"`
	NextAttemptAt  int64  `json:"next_attempt_at" gorm:"index:idx_relay_quota_retry,priority:2"`
	ExpiresAt      int64  `json:"expires_at" gorm:"index"`
	DispatchedAt   int64  `json:"dispatched_at" gorm:"index"`
	LeaseOwner     string `json:"lease_owner" gorm:"type:varchar(128);index"`
	LeaseExpiresAt int64  `json:"lease_expires_at" gorm:"index"`
	LastError      string `json:"last_error" gorm:"type:text"`
	// Violation-fee fields form the durable intent and idempotency marker for the
	// one permitted post-refund penalty on this reservation. They contain only
	// bounded accounting inputs and safe machine failure codes; no provider
	// response, raw error, credential, or user content is persisted.
	ViolationFeeStatus       string `json:"-" gorm:"type:varchar(32);not null;default:'';index"`
	ViolationFeeFailureCode  string `json:"-" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeAttempts     int    `json:"-" gorm:"not null;default:0"`
	ViolationFeeCode         string `json:"-" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeQuota        int    `json:"-" gorm:"not null;default:0"`
	ViolationFeeAmount       string `json:"-" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeGroupRatio   string `json:"-" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeChannelID    int    `json:"-" gorm:"not null;default:0;index"`
	ViolationFeeAuditEventID string `json:"-" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeModelName    string `json:"-" gorm:"type:varchar(255);not null;default:''"`
	ViolationFeeGroup        string `json:"-" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeRequestID    string `json:"-" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeStatusCode   int    `json:"-" gorm:"not null;default:0"`
	ViolationFeeUseTime      int    `json:"-" gorm:"not null;default:0"`
	ViolationFeeIsStream     bool   `json:"-" gorm:"not null;default:false"`
	ViolationFeeUpdatedAt    int64  `json:"-" gorm:"type:bigint;not null;default:0;index"`
	ViolationFeeChargedAt    int64  `json:"-" gorm:"type:bigint;not null;default:0;index"`
	CreatedAt                int64  `json:"created_at" gorm:"index"`
	UpdatedAt                int64  `json:"updated_at" gorm:"index"`
	CompletedAt              int64  `json:"completed_at" gorm:"index"`
}

func (RelayQuotaReservationRecord) TableName() string {
	return "relay_quota_reservations"
}

const (
	RelayQuotaReservationReviewActionRetry         = "retry"
	RelayQuotaReservationReviewActionRetryTaskPoll = "retry_task_poll"
	RelayQuotaReservationReviewActionRetryFee      = "retry_fee"
)

// RelayQuotaReservationReviewEvent is an append-only operator audit entry.
// It is stored in the primary database in the same transaction as the
// reservation state transition, so a successful manual action can neither
// lose its audit record nor leave behind an audit record for a rolled-back
// transition. The immutable accounting snapshot deliberately contains no
// provider payloads, credentials, request bodies, or raw failure text.
type RelayQuotaReservationReviewEvent struct {
	ID             int64  `json:"id" gorm:"primaryKey;autoIncrement"`
	EventID        string `json:"event_id" gorm:"type:varchar(64);not null;uniqueIndex"`
	ReservationID  string `json:"reservation_id" gorm:"type:varchar(64);not null;uniqueIndex:ux_relay_quota_review_revision,priority:1;index"`
	Revision       int    `json:"revision" gorm:"not null;uniqueIndex:ux_relay_quota_review_revision,priority:2"`
	OperatorUserID int    `json:"operator_user_id" gorm:"not null;index"`
	Action         string `json:"action" gorm:"type:varchar(16);not null"`
	FromStatus     string `json:"from_status" gorm:"type:varchar(32);not null"`
	ToStatus       string `json:"to_status" gorm:"type:varchar(32);not null"`
	Operation      string `json:"operation" gorm:"type:varchar(16);not null"`
	// Task fields are populated only for provider-poll retries. Keeping both
	// task status and journal state in the immutable event makes it explicit
	// that accounting stayed settled while the operator reopened polling.
	TaskID                 string `json:"task_id,omitempty" gorm:"type:varchar(191);index"`
	TaskPlatform           string `json:"task_platform,omitempty" gorm:"type:varchar(30)"`
	TaskFromStatus         string `json:"task_from_status,omitempty" gorm:"type:varchar(20)"`
	TaskToStatus           string `json:"task_to_status,omitempty" gorm:"type:varchar(20)"`
	TaskOperationFromState string `json:"task_operation_from_state,omitempty" gorm:"type:varchar(24)"`
	TaskOperationToState   string `json:"task_operation_to_state,omitempty" gorm:"type:varchar(24)"`
	TaskOperationCreatedAt int64  `json:"task_operation_created_at,omitempty" gorm:"type:bigint"`
	TaskOperationAttempts  int    `json:"task_operation_attempts,omitempty"`

	UserID                   int    `json:"user_id" gorm:"not null;index"`
	TokenID                  int    `json:"token_id" gorm:"index"`
	TokenUnlimited           bool   `json:"token_unlimited" gorm:"not null;default:false"`
	TrustQuotaBypassed       bool   `json:"trust_quota_bypassed" gorm:"not null;default:false"`
	ChannelID                int    `json:"channel_id" gorm:"index"`
	FundingSource            string `json:"funding_source" gorm:"type:varchar(32);not null"`
	RequestedQuota           int    `json:"requested_quota" gorm:"not null"`
	ReservedQuota            int    `json:"reserved_quota" gorm:"not null"`
	TokenReserved            int    `json:"token_reserved" gorm:"not null"`
	SubscriptionID           int    `json:"subscription_id" gorm:"index"`
	UsageEpoch               int64  `json:"usage_epoch" gorm:"type:bigint;not null;default:0"`
	ActualQuota              int    `json:"actual_quota" gorm:"not null"`
	ViolationFeeCode         string `json:"violation_fee_code,omitempty" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeQuota        int    `json:"violation_fee_quota,omitempty" gorm:"not null;default:0"`
	ViolationFeeAmount       string `json:"violation_fee_amount,omitempty" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeGroupRatio   string `json:"violation_fee_group_ratio,omitempty" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeChannelID    int    `json:"violation_fee_channel_id,omitempty" gorm:"not null;default:0"`
	ViolationFeeAuditEventID string `json:"violation_fee_audit_event_id,omitempty" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeFromStatus   string `json:"violation_fee_from_status,omitempty" gorm:"type:varchar(32);not null;default:''"`
	ViolationFeeToStatus     string `json:"violation_fee_to_status,omitempty" gorm:"type:varchar(32);not null;default:''"`
	ViolationFeeFailureCode  string `json:"violation_fee_failure_code,omitempty" gorm:"type:varchar(64);not null;default:''"`
	ViolationFeeAttempts     int    `json:"violation_fee_attempts,omitempty" gorm:"not null;default:0"`
	CreatedAt                int64  `json:"created_at" gorm:"not null;index"`
}

func (RelayQuotaReservationReviewEvent) TableName() string {
	return "relay_quota_reservation_review_events"
}
